---
name: main
# Automatically cancel a previous run.
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
# yamllint disable rule:line-length
on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']
jobs:
  run-tests:
    name: Run tests for ${{ matrix.os }} on ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Install TinyTex
        uses: r-lib/actions/setup-tinytex@v2
      - name: Install additional LaTeX packages
        run: |
          tlmgr update --self
          tlmgr install a4wide beamer biber biblatex caption eurosym grfext minibox moreverb ntgclass relsize setspace xfrac
          tlmgr list --only-installed
      - name: Set up Miniforge
        run: |
          if [[ $RUNNER_OS == "Linux" ]]; then
            wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh
          elif [[ $RUNNER_OS == "macOS" ]]; then
            wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh -O miniforge.sh
          elif [[ $RUNNER_OS == "Windows" ]]; then
            curl -L -o miniforge.exe https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Windows-x86_64.exe
            echo "Miniforge setup complete for Windows"
            exit 0
          fi
          bash miniforge.sh -b -p $HOME/miniforge
          echo "$HOME/miniforge/bin" >> $GITHUB_PATH
          source $HOME/miniforge/bin/activate
          conda init bash
      - name: Install Mamba and Environment
        run: |
          source $HOME/miniforge/bin/activate
          conda install -n base -c conda-forge mamba
          mamba env create -f environment.yml
          conda activate eaibgap
          python --version
      - name: Run full test suite on MacOS and Linux
        shell: bash -l {0}
        run: |
          source $HOME/miniforge/bin/activate
          source activate eaibgap
          pytest -v --cov=./ --cov-report=xml
        if: runner.os != 'Windows'
      - name: Run test suite except for pytask build on Windows
        shell: bash -l {0}
        run: |
          source activate eaibgap
          pytest -v -k "not pytask"
        if: runner.os == 'Windows'
      - name: Upload coverage reports
        if: runner.os == 'Linux' && matrix.python-version == '3.12'
        uses: codecov/codecov-action@v3
